name: Coverage

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate coverage report
        run: |
          cargo +nightly tarpaulin --verbose --out lcov
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: lcov.info
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}